// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5egzEk-v1YIwYsNs0avmzt4iJCfEqbg',
    appId: '1:111397515461:web:d6b58835865b89389a00ac',
    messagingSenderId: '111397515461',
    projectId: 'cardgenerate',
    authDomain: 'cardgenerate.firebaseapp.com',
    storageBucket: 'cardgenerate.appspot.com',
  
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRsRdF7OFL1GuQuFX1GhyolvoeD3aJNh8',
    appId: '1:111397515461:android:6d5e256a315116749a00ac',
    messagingSenderId: '111397515461',
    projectId: 'cardgenerate',
    storageBucket: 'cardgenerate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJI8dbB_gjO_h37xuiBJdEp_LQzqosh5s',
    appId: '1:111397515461:ios:e42ab1a251a91a949a00ac',
    messagingSenderId: '111397515461',
    projectId: 'cardgenerate',
    storageBucket: 'cardgenerate.appspot.com',
    iosBundleId: 'com.example.cardgenrate',
  );
}
